name: Build Win69Updater

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --name win69updater win69updater.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: win69updater
        path: dist/win69updater.exe
